name: "Nuntia"
description: "Generate release notes and migration guides from a commit range on demand."
author: "Daniel Chalmers"
branding:
  color: "green"
  icon: "file-text"

inputs:
  base-commit:
    description: "Start commit SHA (inclusive) for the release notes range."
    required: true
  head-commit:
    description: "End commit SHA (inclusive) for the release notes range."
    required: true
  branch:
    description: "Branch name associated with the release notes."
    required: true
  prompt-path:
    description: "Repo-relative path to the prompt template that defines the release notes format."
    required: false
    default: ".github/Nuntia.prompt"
  model:
    description: "Gemini model identifier used to generate release notes."
    required: false
    default: "gemini-3-flash-preview"
  temperature:
    description: "Sampling temperature for the model (0-2)."
    required: false
    default: "1.0"
  max-linked-items:
    description: "Cap on how many linked issues, PRs, or commits are fetched."
    required: false
    default: "3"
  max-reference-depth:
    description: "Depth to follow references inside linked descriptions."
    required: false
    default: "2"

outputs:
  release-notes-path:
    description: "Filesystem path to the generated release notes markdown."
  input-tokens:
    description: "Gemini input token count."
  output-tokens:
    description: "Gemini output token count."

runs:
  using: "node24"
  main: "dist/index.js"
