import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Config, ReleaseContext } from '../src/types';

// src/index.ts runs the action as soon as it is imported, so every collaborator with I/O is mocked and each test imports a fresh copy.
// The prompt module is real, and fetch is stubbed for the tests that set prompt-url.
const mocks = vi.hoisted(() => {
  const summary = { addRaw: vi.fn(), write: vi.fn() };
  return {
    setOutput: vi.fn(),
    setFailed: vi.fn(),
    summary,
    getConfig: vi.fn(),
    buildReleaseContext: vi.fn(),
    generateText: vi.fn(),
  };
});

vi.mock('@actions/core', () => ({
  setOutput: mocks.setOutput,
  setFailed: mocks.setFailed,
  summary: mocks.summary,
}));
vi.mock('../src/env', () => ({ getConfig: mocks.getConfig }));
vi.mock('../src/github', () => ({ GitHubClient: class {} }));
vi.mock('../src/context', async (importActual) => ({
  ...(await importActual<typeof import('../src/context')>()),
  buildReleaseContext: mocks.buildReleaseContext,
}));
vi.mock('../src/llm/chat', async (importActual) => ({
  ...(await importActual<typeof import('../src/llm/chat')>()),
  ChatClient: class {
    generateText = mocks.generateText;
  },
}));

const CONFIG: Config = {
  owner: 'acme',
  repo: 'widgets',
  branch: 'main',
  baseCommit: 'base',
  headCommit: 'head',
  token: 'token',
  promptUrl: '',
  model: 'gemini-flash-latest',
  endpoint: {
    provider: 'gemini',
    model: 'gemini-flash-latest',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    host: 'generativelanguage.googleapis.com',
    apiKey: 'gemini-key',
    keyName: 'GEMINI_API_KEY',
    isDefault: true,
  },
  maxLinkedItems: 5,
  maxReferenceDepth: 2,
  maxItemLength: 5000,
};

const CONTEXT: ReleaseContext = {
  generatedAt: '2024-01-01T00:00:00.000Z',
  inputs: {
    baseCommit: 'base',
    headCommit: 'head',
    branch: 'main',
    promptUrl: CONFIG.promptUrl,
    model: CONFIG.model,
    maxLinkedItems: 5,
    maxReferenceDepth: 2,
    maxItemLength: 5000,
  },
  repository: { owner: 'acme', repo: 'widgets', branch: 'main' },
  range: { base: 'base', head: 'head', totalCommits: 2, changedFiles: [] },
  commits: [],
  linkedItems: [],
};

const BUNDLED_PROMPT = fs.readFileSync(new URL('../examples/Nuntia.prompt', import.meta.url), 'utf8');

const ATTRIBUTION =
  '<!-- Do not remove this attribution notice -->\n*These release notes were initially generated by Nuntia. [Learn more](http://github.com/danielchalmers/Nuntia)*';

let tempDir: string;

async function runAction() {
  vi.resetModules();
  await import('../src/index');
  await vi.waitFor(() => {
    if (mocks.setOutput.mock.calls.length === 0 && mocks.setFailed.mock.calls.length === 0) {
      throw new Error('action has not finished');
    }
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nuntia-'));
  vi.spyOn(process, 'cwd').mockReturnValue(tempDir);
  vi.spyOn(console, 'log').mockImplementation(() => {});
  vi.stubEnv('GITHUB_STEP_SUMMARY', '');
  mocks.summary.addRaw.mockReturnValue(mocks.summary);
  mocks.summary.write.mockResolvedValue(mocks.summary);
  mocks.getConfig.mockReturnValue(CONFIG);
  mocks.buildReleaseContext.mockResolvedValue(CONTEXT);
  mocks.generateText.mockResolvedValue({
    text: '## What changed\n\n- Fixed a bug\n\n',
    inputTokens: 1200,
    cachedInputTokens: 0,
    outputTokens: 340,
    reasoningTokens: 900,
  });
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
  fs.rmSync(tempDir, { recursive: true, force: true });
});

describe('Nuntia action entry point', () => {
  it('writes the notes with the attribution footer and sets the action outputs', async () => {
    await runAction();

    const notesPath = path.join(tempDir, 'artifacts', 'nuntia-release-notes.md');
    expect(fs.readFileSync(notesPath, 'utf8')).toBe(`## What changed\n\n- Fixed a bug\n\n${ATTRIBUTION}\n`);
    expect(mocks.setOutput).toHaveBeenCalledWith('release-notes-path', notesPath);
    expect(mocks.setOutput).toHaveBeenCalledWith('input-tokens', '1200');
    expect(mocks.setOutput).toHaveBeenCalledWith('output-tokens', '340');
    expect(mocks.setFailed).not.toHaveBeenCalled();
  });

  it('sends the bundled prompt and the release context to the configured model when prompt-url is blank', async () => {
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);

    await runAction();

    const [request] = mocks.generateText.mock.calls[0]!;
    expect(Object.keys(request)).toEqual(['model', 'systemPrompt', 'userPrompt']);
    expect(request.model).toBe('gemini-flash-latest');
    expect(request.systemPrompt).toBe(BUNDLED_PROMPT);
    expect(request.userPrompt).toContain('"totalCommits": 2');
    expect(fetchMock).not.toHaveBeenCalled();
    expect(console.log).toHaveBeenCalledWith('Prompt: built-in');
  });

  it('sends the prompt at prompt-url when it is set, and logs the url', async () => {
    mocks.getConfig.mockReturnValue({ ...CONFIG, promptUrl: 'https://example.com/prompt.txt' });
    vi.stubGlobal('fetch', vi.fn(async () => new Response('Write release notes.')));

    await runAction();

    const [request] = mocks.generateText.mock.calls[0]!;
    expect(request.systemPrompt).toBe('Write release notes.');
    expect(console.log).toHaveBeenCalledWith('Prompt: https://example.com/prompt.txt');
  });

  it('fails before reading the release when prompt-url cannot be fetched', async () => {
    mocks.getConfig.mockReturnValue({ ...CONFIG, promptUrl: 'https://example.com/missing.txt' });
    vi.stubGlobal('fetch', vi.fn(async () => new Response('Not Found', { status: 404, statusText: 'Not Found' })));

    await runAction();

    expect(mocks.setFailed).toHaveBeenCalledWith(expect.stringContaining('Failed to fetch prompt from https://example.com/missing.txt: 404 Not Found.'));
    expect(mocks.buildReleaseContext).not.toHaveBeenCalled();
    expect(mocks.generateText).not.toHaveBeenCalled();
    expect(fs.existsSync(path.join(tempDir, 'artifacts'))).toBe(false);
  });

  it('logs the model and its host', async () => {
    await runAction();

    expect(console.log).toHaveBeenCalledWith('Model: gemini-flash-latest at generativelanguage.googleapis.com (default for GEMINI_API_KEY)');
  });

  it('reports generated tokens without reasoning as output-tokens', async () => {
    await runAction();

    expect(mocks.setOutput).toHaveBeenCalledWith('output-tokens', '340');
  });

  it('writes the payload and context debug artifacts', async () => {
    await runAction();

    const artifacts = path.join(tempDir, 'artifacts');
    expect(JSON.parse(fs.readFileSync(path.join(artifacts, 'nuntia-context.json'), 'utf8'))).toEqual(CONTEXT);
    expect(JSON.parse(fs.readFileSync(path.join(artifacts, 'nuntia-payload.json'), 'utf8'))).toEqual(mocks.generateText.mock.calls[0]![0]);
  });

  it('skips the step summary outside a workflow run', async () => {
    await runAction();

    expect(mocks.summary.write).not.toHaveBeenCalled();
  });

  it('adds the notes to the step summary when running in a workflow', async () => {
    vi.stubEnv('GITHUB_STEP_SUMMARY', path.join(tempDir, 'summary.md'));

    await runAction();

    expect(mocks.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining('- Fixed a bug'));
    expect(mocks.summary.addRaw).toHaveBeenCalledWith(expect.stringContaining(ATTRIBUTION));
    expect(mocks.summary.write).toHaveBeenCalled();
  });

  it('fails the action with the error message and writes nothing when a step throws', async () => {
    mocks.buildReleaseContext.mockRejectedValue(new Error('Commit range base..head is incomplete'));

    await runAction();

    expect(mocks.setFailed).toHaveBeenCalledWith('Commit range base..head is incomplete');
    expect(mocks.setOutput).not.toHaveBeenCalled();
    expect(fs.existsSync(path.join(tempDir, 'artifacts'))).toBe(false);
  });

  it('keeps the debug artifacts but writes no notes, summary, or outputs when generation fails', async () => {
    vi.stubEnv('GITHUB_STEP_SUMMARY', path.join(tempDir, 'summary.md'));
    mocks.generateText.mockRejectedValue(new Error('generativelanguage.googleapis.com stopped the reply at the output token limit'));

    await runAction();

    const artifacts = path.join(tempDir, 'artifacts');
    expect(mocks.setFailed).toHaveBeenCalledWith('generativelanguage.googleapis.com stopped the reply at the output token limit');
    expect(mocks.setOutput).not.toHaveBeenCalled();
    expect(mocks.summary.write).not.toHaveBeenCalled();
    expect(fs.existsSync(path.join(artifacts, 'nuntia-release-notes.md'))).toBe(false);
    expect(JSON.parse(fs.readFileSync(path.join(artifacts, 'nuntia-context.json'), 'utf8'))).toEqual(CONTEXT);
    expect(JSON.parse(fs.readFileSync(path.join(artifacts, 'nuntia-payload.json'), 'utf8'))).toMatchObject({
      model: 'gemini-flash-latest',
    });
  });
});
