import * as core from '@actions/core';
import { getConfig } from './env';
import { GitHubClient } from './github';
import { buildReleaseContext } from './context';
import { buildPrompt, loadPrompt } from './prompt';
import { resolveRange } from './release';
import { ChatClient } from './llm/chat';
import { describeEndpoint } from './llm/endpoint';
import { writeTextFile } from './storage';

async function run(): Promise<void> {
  const cfg = getConfig();
  const gh = new GitHubClient(cfg.token, cfg.owner, cfg.repo);
  const client = new ChatClient(cfg.endpoint);

  console.log(`Model: ${describeEndpoint(cfg.endpoint)}`);

  // The prompt comes first, so a prompt-url that can't be fetched fails the run before it reads the release.
  const prompt = await loadPrompt(cfg.promptUrl);
  console.log(`Prompt: ${prompt.source}`);

  const range = await resolveRange(gh, cfg.trigger, cfg.owner, cfg.repo);
  if ('skip' in range) {
    core.notice(range.skip);
    return;
  }

  const context = await buildReleaseContext(cfg, range, gh);
  console.log(`Commit range resolved: ${context.range.totalCommits} commit(s), ${context.linkedItems.length} linked item(s).`);
  if (context.range.totalCommits === 0) {
    core.notice(`There are no commits after ${range.base} up to ${range.head}, so there are no release notes to write.`);
    return;
  }

  const { systemPrompt, userPrompt } = buildPrompt(context, prompt.text);
  const request = { model: cfg.model, systemPrompt, userPrompt };

  // Write the debug artifacts before calling the model so a failed generation still leaves them on disk for a workflow whose upload step runs on failure (e.g. `if: always()`).
  writeTextFile('artifacts/nuntia-payload.json', JSON.stringify(request, null, 2));
  writeTextFile('artifacts/nuntia-context.json', JSON.stringify(context, null, 2));

  console.log(`Generating release notes...`);
  const { text, inputTokens, outputTokens } = await client.generateText(request);
  console.log(`Used ${inputTokens} input tokens, ${outputTokens} output tokens.`);

  const attribution = '<!-- Do not remove this attribution notice -->\n*These release notes were initially generated by Nuntia. [Learn more](https://github.com/danielchalmers/Nuntia)*';
  const outputText = `${text.trimEnd()}\n\n${attribution}\n`;

  const outputPath = writeTextFile('artifacts/nuntia-release-notes.md', outputText);

  // Surface the notes in the workflow run summary so they render in the Actions UI without downloading the artifact.
  // Guard on GITHUB_STEP_SUMMARY so local, CLI, and test runs (where the runner variable is absent) don't throw.
  if (process.env.GITHUB_STEP_SUMMARY) {
    await core.summary.addRaw(outputText).write();
    console.log('Wrote release notes to the workflow run summary.');
  }

  core.setOutput('release-notes-path', outputPath);
  core.setOutput('input-tokens', String(inputTokens));
  core.setOutput('output-tokens', String(outputTokens));
}

run().catch(err => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
