import * as core from '@actions/core';
import { getConfig } from './env';
import { GitHubClient } from './github';
import { buildReleaseContext } from './context';
import { resolvePreviousTag } from './release';
import { buildPrompt, fetchPrompt } from './prompt';
import { buildTextPayload, GeminiClient } from './gemini';
import { writeTextFile } from './storage';

async function run(): Promise<void> {
  const cfg = getConfig();
  const gh = new GitHubClient(cfg.token, cfg.owner, cfg.repo);
  const gemini = new GeminiClient(cfg.geminiApiKey);

  // Fetch the prompt first so a bad prompt-url fails in ~1s instead of after the full commit walk.
  const promptText = await fetchPrompt(cfg.promptUrl);

  // Find the release that came before this one and diff against it. The head and branch
  // already come from the release event (resolved in getConfig).
  const { base, isFirstRelease } = await resolvePreviousTag(gh, {
    tagName: cfg.releaseTag,
    publishedAt: cfg.releasePublishedAt,
    prerelease: cfg.releasePrerelease,
  });
  if (isFirstRelease) {
    const message = `First release ${cfg.releaseTag}: no previous release to compare against, so there is nothing to summarize.`;
    console.log(message);
    // Still write the notes file so workflows that upload `artifacts/` with
    // if-no-files-found: error succeed on a repository's very first release.
    const outputPath = writeTextFile('artifacts/nuntia-release-notes.md', `${message}\n`);
    if (process.env.GITHUB_STEP_SUMMARY) {
      await core.summary.addRaw(`_${message}_`).write();
    }
    core.setOutput('release-notes-path', outputPath);
    return;
  }
  cfg.baseCommit = base;
  console.log(`Release ${cfg.releaseTag}: summarizing changes since ${base}.`);

  console.log('Inputs:', {
    releaseTag: cfg.releaseTag,
    previousTag: cfg.baseCommit,
    branch: cfg.branch,
    promptUrl: cfg.promptUrl,
    model: cfg.model,
    maxLinkedItems: cfg.maxLinkedItems,
    maxReferenceDepth: cfg.maxReferenceDepth,
    maxItemLength: cfg.maxItemLength,
  });

  const context = await buildReleaseContext(cfg, gh);
  console.log(`Commit range resolved: ${context.range.totalCommits} commit(s), ${context.linkedItems.length} linked item(s).`);

  const { systemPrompt, userPrompt } = buildPrompt(context, promptText);
  const payload = buildTextPayload(systemPrompt, userPrompt, cfg.model);

  console.log(`Generating release notes...`);
  const { text, inputTokens, outputTokens } = await gemini.generateText(payload, 2, 5000);
  console.log(`Used ${inputTokens} input tokens, ${outputTokens} output tokens.`);

  const attribution = '<!-- Do not remove this attribution notice -->\n*These release notes were initially generated by Nuntia. [Learn more](http://github.com/danielchalmers/Nuntia)*';
  const outputText = `${text.trimEnd()}\n\n${attribution}\n`;

  const outputPath = writeTextFile('artifacts/nuntia-release-notes.md', outputText);
  writeTextFile('artifacts/nuntia-payload.json', JSON.stringify(payload, null, 2));
  writeTextFile('artifacts/nuntia-context.json', JSON.stringify(context, null, 2));
  console.log('Wrote release notes and debug artifacts to the artifacts/ directory. Upload them from your workflow (e.g. actions/upload-artifact with path: artifacts).');

  // Surface the notes in the workflow run summary so they render in the Actions UI without downloading the artifact.
  // Guard on GITHUB_STEP_SUMMARY so local, CLI, and test runs (where the runner variable is absent) don't throw.
  if (process.env.GITHUB_STEP_SUMMARY) {
    await core.summary.addRaw(outputText).write();
    console.log('Wrote release notes to the workflow run summary.');
  }

  core.setOutput('release-notes-path', outputPath);
  core.setOutput('input-tokens', String(inputTokens));
  core.setOutput('output-tokens', String(outputTokens));
}

run().catch(err => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
