import * as core from '@actions/core';
import { getConfig } from './env';
import { GitHubClient } from './github';
import { buildReleaseContext } from './context';
import { buildPrompt, fetchPrompt } from './prompt';
import { buildTextPayload, GeminiClient } from './gemini';
import { writeTextFile } from './storage';
import { uploadArtifact } from './artifacts';

async function run(): Promise<void> {
  const cfg = getConfig();
  const gh = new GitHubClient(cfg.token, cfg.owner, cfg.repo);
  const gemini = new GeminiClient(cfg.geminiApiKey);

  console.log('Inputs:', {
    baseCommit: cfg.baseCommit,
    headCommit: cfg.headCommit,
    branch: cfg.branch,
    promptUrl: cfg.promptUrl,
    model: cfg.model,
    temperature: cfg.temperature,
    maxLinkedItems: cfg.maxLinkedItems,
    maxReferenceDepth: cfg.maxReferenceDepth,
    maxItemBodyLength: cfg.maxItemBodyLength,
  });

  const context = await buildReleaseContext(cfg, gh);
  console.log(`Commit range resolved: ${context.commits.length} commit(s), ${context.linkedItems.length} linked item(s).`);

  const promptText = await fetchPrompt(cfg.promptUrl);
  const { systemPrompt, userPrompt } = buildPrompt(context, promptText);
  const payload = buildTextPayload(systemPrompt, userPrompt, cfg.model, cfg.temperature);

  console.log(`Generating release notes...`);
  const { text, inputTokens, outputTokens } = await gemini.generateText(payload, 2, 5000);
  console.log(`Used ${inputTokens} input tokens, ${outputTokens} output tokens.`);

  const attribution = '<!-- Do not remove this attribution notice -->\n*These release notes were initially generated by Nuntia. [Learn more](http://github.com/danielchalmers/Nuntia)*';
  const outputText = `${text.trimEnd()}\n\n${attribution}\n`;

  const artifactName = 'nuntia-release-notes';
  const outputPath = writeTextFile('artifacts/nuntia-release-notes.md', outputText);
  const payloadPath = writeTextFile('artifacts/nuntia-payload.json', JSON.stringify(payload, null, 2));
  await uploadArtifact(artifactName, [outputPath, payloadPath]);

  core.setOutput('release-notes-path', outputPath);
  core.setOutput('input-tokens', String(inputTokens));
  core.setOutput('output-tokens', String(outputTokens));
}

run().catch(err => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
